In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("netflix_titles_unclean_dataset.csv")

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

In [6]:
df.shape

(7787, 12)

In [7]:
df.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [11]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [12]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [15]:
df.duplicated().sum()

0

In [16]:
df['show_id'].duplicated().sum()

0

In [17]:
df['type'].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [18]:
df['rating'].value_counts(dropna=False)

rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
NaN            7
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

In [19]:
df['duration'].value_counts(dropna=False).head(20)

duration
1 Season     1608
2 Seasons     382
3 Seasons     184
90 min        136
93 min        131
94 min        125
91 min        125
95 min        119
92 min        118
97 min        117
96 min        115
98 min        106
103 min       101
99 min        101
88 min        101
102 min        98
100 min        97
106 min        97
101 min        96
86 min         93
Name: count, dtype: int64

In [20]:
df['date_added'].head(10)

0      August 14, 2020
1    December 23, 2016
2    December 20, 2018
3    November 16, 2017
4      January 1, 2020
5         July 1, 2017
6         June 1, 2020
7     November 1, 2019
8        April 1, 2019
9    December 15, 2017
Name: date_added, dtype: object

In [21]:
df['show_id'].duplicated().sum()

0

In [22]:
df[df['duration'].isnull()][['type', 'title', 'duration']]

Empty DataFrame
Columns: [type, title, duration]
Index: []

In [23]:
df[df['rating'].isnull()][['type', 'title', 'rating']]

         type                                              title rating
67      Movie  13TH: A Conversation with Oprah Winfrey & Ava ...    NaN
2359  TV Show                  Gargantia on the Verdurous Planet    NaN
3660  TV Show                                       Little Lunch    NaN
3736    Movie                                    Louis C.K. 2017    NaN
3737    Movie                              Louis C.K.: Hilarious    NaN
3738    Movie               Louis C.K.: Live at the Comedy Store    NaN
4323    Movie                               My Honor Was Loyalty    NaN

In [24]:
df[['director', 'cast', 'country', 'date_added']].isnull().sum()

director      2389
cast           718
country        507
date_added      10
dtype: int64

In [25]:
df[['director', 'cast', 'country', 'date_added']].isnull().mean() * 100

director      30.679337
cast           9.220496
country        6.510851
date_added     0.128419
dtype: float64

In [26]:
df['type'].unique()

array(['TV Show', 'Movie'], dtype=object)

In [27]:
df['rating'].unique()

array(['TV-MA', 'R', 'PG-13', 'TV-14', 'TV-PG', 'NR', 'TV-G', 'TV-Y', nan,
       'TV-Y7', 'PG', 'G', 'NC-17', 'TV-Y7-FV', 'UR'], dtype=object)

In [28]:
df['country'].head(20)

0                             Brazil
1                             Mexico
2                          Singapore
3                      United States
4                      United States
5                             Turkey
6                              Egypt
7                      United States
8                              India
9                              India
10                     United States
11             Poland, United States
12                            Mexico
13                          Thailand
14                     United States
15                           Nigeria
16                               NaN
17    Norway, Iceland, United States
18                             India
19                    United Kingdom
Name: country, dtype: object

In [29]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Unknown')

In [30]:
df[['director', 'cast', 'country', 'rating']].isnull().sum()

director    0
cast        0
country     0
rating      0
dtype: int64

In [31]:
df['date_added'] = pd.to_datetime(
    df['date_added'],
    errors='coerce'
)

In [32]:
df['date_added'].dtype

dtype('<M8[ns]')

In [33]:
df['date_added'].isnull().sum()

98

In [34]:
df[df['date_added'].notna()]['date_added'].head(20)

0    2020-08-14
1    2016-12-23
2    2018-12-20
3    2017-11-16
4    2020-01-01
5    2017-07-01
6    2020-06-01
7    2019-11-01
8    2019-04-01
9    2017-12-15
10   2017-10-20
11   2018-11-30
12   2019-05-17
13   2019-03-01
14   2020-03-19
15   2019-09-01
16   2019-03-20
17   2018-10-10
18   2019-03-29
19   2018-05-16
Name: date_added, dtype: datetime64[ns]

In [35]:
df[df['date_added'].notna()]['date_added'].tail(20)

7767   2016-12-15
7768   2018-10-01
7769   2019-12-15
7770   2016-03-09
7771   2018-08-10
7772   2017-07-01
7773   2019-11-01
7774   2019-11-20
7775   2020-08-14
7776   2018-11-01
7777   2019-07-01
7778   2019-11-01
7779   2019-11-26
7780   2018-07-01
7781   2020-01-11
7782   2020-10-19
7783   2019-03-02
7784   2020-09-25
7785   2020-10-31
7786   2020-03-01
Name: date_added, dtype: datetime64[ns]

In [36]:
df['date_added'].isnull().sum()

98

In [39]:
raw_df = pd.read_csv("netflix_titles_unclean_dataset.csv")

In [40]:
df['date_added'] = pd.to_datetime(
    raw_df['date_added'],
    format='%B %d, %Y',
    errors='coerce'
)

In [41]:
df['date_added'].isnull().sum()

98

In [42]:
df['date_added'] = pd.to_datetime(
    raw_df['date_added'],
    format='mixed',
    errors='coerce'
)

In [43]:
df['date_added'].isnull().sum()

10

In [44]:
df[['type', 'duration']].head(20)

       type   duration
0   TV Show  4 Seasons
1     Movie     93 min
2     Movie     78 min
3     Movie     80 min
4     Movie    123 min
5   TV Show   1 Season
6     Movie     95 min
7     Movie    119 min
8     Movie    118 min
9     Movie    143 min
10    Movie    103 min
11  TV Show   1 Season
12  TV Show   1 Season
13    Movie     89 min
14    Movie     91 min
15    Movie    149 min
16  TV Show   1 Season
17    Movie    144 min
18    Movie    124 min
19    Movie     87 min

In [45]:
df['duration'].isnull().sum()

0

In [46]:
df['duration'].value_counts().head(20)

duration
1 Season     1608
2 Seasons     382
3 Seasons     184
90 min        136
93 min        131
94 min        125
91 min        125
95 min        119
92 min        118
97 min        117
96 min        115
98 min        106
103 min       101
99 min        101
88 min        101
102 min        98
100 min        97
106 min        97
101 min        96
86 min         93
Name: count, dtype: int64

In [47]:
df['duration_minutes'] = df['duration'].where(
    df['type'] == 'Movie'
).str.extract(r'(\d+)')[0].astype(float)

In [48]:
df['seasons'] = df['duration'].where(
    df['type'] == 'TV Show'
).str.extract(r'(\d+)')[0].astype(float)

In [49]:
df[['type', 'duration', 'duration_minutes', 'seasons']].head(20)

       type   duration  duration_minutes  seasons
0   TV Show  4 Seasons               NaN      4.0
1     Movie     93 min              93.0      NaN
2     Movie     78 min              78.0      NaN
3     Movie     80 min              80.0      NaN
4     Movie    123 min             123.0      NaN
5   TV Show   1 Season               NaN      1.0
6     Movie     95 min              95.0      NaN
7     Movie    119 min             119.0      NaN
8     Movie    118 min             118.0      NaN
9     Movie    143 min             143.0      NaN
10    Movie    103 min             103.0      NaN
11  TV Show   1 Season               NaN      1.0
12  TV Show   1 Season               NaN      1.0
13    Movie     89 min              89.0      NaN
14    Movie     91 min              91.0      NaN
15    Movie    149 min             149.0      NaN
16  TV Show   1 Season               NaN      1.0
17    Movie    144 min             144.0      NaN
18    Movie    124 min             124.0      NaN
19    Movie     87 min              87.0      NaN

In [51]:
df[['duration_minutes', 'seasons']].notnull().sum()

duration_minutes    5377
seasons             2410
dtype: int64

In [52]:
df.isnull().sum()

show_id                0
type                   0
title                  0
director               0
cast                   0
country                0
date_added            10
release_year           0
rating                 0
duration               0
listed_in              0
description            0
duration_minutes    2410
seasons             5377
dtype: int64

In [53]:
df['rating'].value_counts()

rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
Unknown        7
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

In [54]:
df['type'].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [55]:
df['release_year'].min(), df['release_year'].max()

(1925, 2021)

In [56]:
df.dtypes

show_id                     object
type                        object
title                       object
director                    object
cast                        object
country                     object
date_added          datetime64[ns]
release_year                 int64
rating                      object
duration                    object
listed_in                   object
description                 object
duration_minutes           float64
seasons                    float64
dtype: object

In [57]:
df['country'].value_counts().head(20)

country
United States                    2555
India                             923
Unknown                           507
United Kingdom                    397
Japan                             226
South Korea                       183
Canada                            177
Spain                             134
France                            115
Egypt                             101
Mexico                            100
Turkey                            100
Australia                          83
Taiwan                             78
Brazil                             72
Philippines                        71
Nigeria                            70
Indonesia                          70
United Kingdom, United States      64
Germany                            61
Name: count, dtype: int64

In [58]:
df['listed_in'].value_counts().head(20)

listed_in
Documentaries                                        334
Stand-Up Comedy                                      321
Dramas, International Movies                         320
Comedies, Dramas, International Movies               243
Dramas, Independent Movies, International Movies     215
Kids' TV                                             205
Children & Family Movies                             177
Documentaries, International Movies                  172
Children & Family Movies, Comedies                   169
Comedies, International Movies                       161
Dramas, International Movies, Romantic Movies        153
Comedies, International Movies, Romantic Movies      139
Dramas                                               117
Action & Adventure, Dramas, International Movies     117
International TV Shows, TV Dramas                    111
Dramas, International Movies, Thrillers              109
Crime TV Shows, International TV Shows, TV Dramas    106
Comedies, Dramas, Independent Movies                 101
Action & Adventure                                    99
Comedies                                              97
Name: count, dtype: int64

In [59]:
df.isnull().sum()

show_id                0
type                   0
title                  0
director               0
cast                   0
country                0
date_added            10
release_year           0
rating                 0
duration               0
listed_in              0
description            0
duration_minutes    2410
seasons             5377
dtype: int64

In [60]:
df.duplicated().sum()

0

In [61]:
df.to_csv("netflix_titles_Cleaned_dataset", index=False)

In [64]:
import os
os.path.exists("netflix_titles_Cleaned_dataset")

True

In [65]:
df.shape

(7787, 14)